### ISSUE TITLE
Doesn't work for version 334.1.0.34.118

### ISSUE THREAD

**Issue by visualsayed** [phwd/fb-ios-pinning-2021#1]
Hi Philippe,

Thanks for this nice script but could you please let me know which FB version it works with?

Thanks,
Sayed

**Comment by phwd** [comment]
Facebook 333.0 (when the Frida script was made)
Facebook 336.0 (downloaded latest from TestFlight)

**Comment by phwd** [comment]
Closing this.

**Comment by visualsayed** [comment]
Hi Philippe,

Thank you very much for your support here, unfortunately I can't get it to work but it seems that your code is working perfectly although May I ask you about the proxy app that you uses in intercepting, is it Burp or another tool?

Thanks,
Sayed

**Comment by phwd** [comment]
Hi Sayed,

It's Burp Suite as the proxy.

**Comment by visualsayed** [comment]
Hi Philippe,

Thank you very much for the info, strangely I keep getting "Remote host terminated the handshake" error with latest FB on IOS 14.3 

Thanks,
Sayed

**Comment by phwd** [comment]
Hi Sayed, <img width="1004" alt="Screenshot 2021-10-13 at 5 52 13 PM" src="https://user-images.githubusercontent.com/402933/137217896-cdab6927-cb53-45e5-af81-b5cae0c32fe3.png">
I'm not sure what to say, it's possible the version or config for the app you're downloading doesn't use this flow.
I just tried it and it worked for me.
